# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.4'
- task: CmdLine@2
  inputs:
    script: |
      xcode-select --install
      bundle install
      bundle exec fastlane ios test
